# docker-compose.yml
version: '3.8'

services:
  # База данных
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # Бэкенд
  backend:
    build: ./server
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped

  # Фронтенд (nginx)
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   # depends_on:
     # - backend
    restart: unless-stopped

volumes:
  mongodb_data: